name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: dev
    steps:
      - uses: actions/checkout@v4
        # with:
        #   token: ${{ secrets.PERSONAL_TOKEN }}
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Update Testomat test cases
        env:
          TESTOMATIO: ${{ secrets.TESTOMATIO }}
        run: |
          npm run test:check
          # git status  # Check if files were modified
          # git config --global core.autocrlf false
          # git config --local user.email "thien.dang@ncc.asia"
          # git config --local user.name "githubaction"
          # git add -A
          # if [[ -n $(git diff --cached) ]]; then
          #   echo "changes=true" >> $GITHUB_ENV
          #   git commit -m "Automated update Testomat ids" --no-verify
          #   git push
          # else
          #   echo "changes=false" >> $GITHUB_ENV
          # fi
      - name: Run tests
        # if: env.changes == 'false'  # Only run if there are no changes
        env:
          GH_PAT: ${{ secrets.PERSONAL_TOKEN }}
          BASE_URL: ${{ secrets.BASE_URL }}
          TESTOMATIO: ${{ secrets.TESTOMATIO }}
          TESTOMATIO_RUNGROUP_TITLE: ${{ secrets.TESTOMATIO_RUNGROUP_TITLE }}
        run: PLAYWRIGHT_JSON_OUTPUT_NAME=results.json npx playwright test
      - uses: daun/playwright-report-summary@v3
        if: always()
        with:
          github-token: ${{ github.token }}
          report-file: results.json
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
